routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//Route::get('/users', 'UserController@index')->name('users');
//Route::get('/users/{id}/edit', 'UserController@edit')->name('users.update');
//Route::post('/users/{id}/edit', 'UserController@update');


Route::resources([
    'users' => 'UserController',
    'interview' => 'InterviewController',
    'interviewtype' => 'InterviewTypeController',
]);

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(15);

        return view('users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all()->pluck('name', 'id');

        return view('users.add', ['roles' => $roles]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6',
            'phone' => 'required|string|min:6',
            'is_active' => 'required|boolean',
            'role_id' => 'exists:roles,id',
        ]);
        //dd($data);

        $user = User::create([
            'first_name' => $data['first_name'],
            'last_name' => $data['last_name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
            'role_id'   => $data['role_id'],
            'is_active' => $data['is_active'],
        ]);

        return view('users.show', ['user' => $user]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $data = $request->validate([
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            //'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required|string|min:6',
            'is_active' => 'required|boolean',
        ]);

        //dd($data);

        $user->update([
            'first_name' => $data['first_name'],
            'last_name' => $data['last_name'],
            //'email' => $data['email'],
            'phone' => $data['phone'],
            //'role_id'   => Role::where('name', 'student')->first()->id,
            'is_active' => $data['is_active'],
        ]);

        return redirect()->route('users.show', $user->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('users.index');
    }

}

resources/views/users/add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create user</div>

                    <div class="panel-body">
                        {{ Form::open(array('route' => array('users.store'), 'method' => 'post')) }}
                        <div>
                            {{ Form::label('first_name', 'First name') }}</div>
                        <div>
                            {{ Form::text('first_name') }}
                        </div>
                        <div>
                            {{ Form::label('last_name', 'Last name') }}</div>
                        <div>
                            {{ Form::text('last_name') }}
                        </div>
                        <div>
                            {{ Form::label('email', 'email') }}</div>
                        <div>
                            {{ Form::text('email') }}
                        </div>
                        <div>
                            {{ Form::label('Phone', 'phone') }}</div>
                        <div>
                            {{ Form::text('phone') }}
                        </div>
                        <div>
                            {{ Form::label('password', 'Password') }}</div>
                        <div>
                            {{ Form::password('password') }}
                        </div>
                        <div>
                            {{ Form::label('role_id', 'Role') }}</div>
                        <div>
                            {{ Form::select('role_id', $roles) }}
                        </div>
                        <div>
                            {{ Form::label('is_active', 'Active') }}</div>
                        <div>
                            {{ Form::checkbox('is_active') }}
                        </div>
                        <div>
                            {{ csrf_field() }}
                            {{  Form::submit('Save') }}
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit user:{{ $user->last_name }} {{ $user->first_name }}</div>

                    <div class="panel-body">
                        {{ Form::model($user, array('route' => array('users.update', $user->id))) }}
                        <div>
                            {{ Form::label('first_name', 'First name') }}</div>
                        <div>
                            {{ Form::text('first_name') }}
                        </div>
                        <div>
                            {{ Form::label('last_name', 'Last name') }}</div>
                        <div>
                            {{ Form::text('last_name') }}
                        </div>
                        <div>
                            {{ Form::label('email', 'email') }}</div>
                        <div>
                            {{ Form::text('email', $user->email, array('disabled' => 'disabled')) }}
                        </div>
                        <div>
                            {{ Form::label('phone', 'phone') }}</div>
                        <div>
                            {{ Form::text('phone') }}
                        </div>
                        <div>
                            {{ Form::label('is_active', 'Active') }}</div>
                        <div>
                            {{ Form::checkbox('is_active') }}
                        </div>
                        <div>
                            {{ method_field('PUT') }}
                            {{ csrf_field() }}
                            {{  Form::submit('Save') }}
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Users</div>

                    <div class="panel-body">
                        <table class="table">
                            <thead class="">
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Status</th>
                                <th>Registered At</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->last_name }} {{ $user->first_name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->role->name }}</td>
                                    <td>{{ $user->is_active }}</td>
                                    <td>{{ $user->created_at }}</td>
                                    <td>{{ Html::link(route('users.edit', ['id' => $user->id]), 'Edit')}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ Html::link(route('users.create'), 'Add User')}}
                        {{ $users->links('vendor.pagination.bootstrap-4') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ $user->last_name }} {{ $user->first_name }}</div>

                    <div class="panel-body">
                        <div>
                            Email:
                            {{ $user->email }}
                        </div>
                        <div>
                            Phone:
                            {{ $user->phone }}
                        </div>
                        <div>
                            Is Active:
                            @if($user->is_active) Yes @else No @endif
                        </div>
                        <div>
                            Role: {{ $user->role->name }}
                        </div>
                        <div>
                            {{ Html::link(route('users.edit', ['id' => $user->id]), 'Edit', ['class' => 'btn btn-default'])}}

                            {{ Form::model($user, array('route' => array('users.destroy', $user->id))) }}
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                            {{  Form::submit('Delete') }}
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection